name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_FROZEN: true

jobs:
  core-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    env:
      COVERAGE_FLAGS: "--cov=src/airball --cov-report=xml --cov-report=term-missing  --cov-fail-under=90"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.10"
          python-version: ${{ matrix.python_version }}

      - name: Install AIRBALL and dependencies
        run: uv sync

      - name: Run python tests
        run: uv run pytest $COVERAGE_FLAGS
